<label>Team
    <input type="number" name="team" 
    value="<?php echo Request::post("team") ?>" />
  </label>

  <label>League name
    <input type="text" name="league_name"
    value="<?php echo Request::post("league_name") ?>" />
  </label>

  <label>Cup name
    <input type="text" name="cup_name"
    value="<?php echo Request::post("cup_name") ?>" />
  </label>

  <label>Supercup name
    <input type="text" name="supercup_name"
    value="<?php echo Request::post("supercup_name") ?>" />
  </label>

  <label>Times won league
    <input type="number" name="times_won_league" 
    value="<?php echo Request::post("times_won_league") ?>" />
  </label>

  <label>Times won cup
    <input type="number" name="times_won_cup" 
    value="<?php echo Request::post("times_won_cup") ?>" />
  </label>

  <label>Times won supercup
    <input type="number" name="times_won_supercup" 
    value="<?php echo Request::post("times_won_supercup") ?>" />
  </label>