<a href="<?php echo App::config("url") ?>trophy/prepareadd" class="success button expanded">
    ADD NEW TROPHY
</a>
<table>
    <thead>
        <tr>
            <th>Trophy name</th>
            <th>Team</th>
            <th>Times won</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($trophys as $trophy): ?>
        <?php foreach ($team_trophys as $tt): ?>
        <tr>
            <?php if($trophy->trophy_name === $tt->trophy_name): ?>
            <a href="<?= App::config("url")?>/team_trophys/index/<?= $tt->trophy?>"> <?= $trophy->trophy_name ?></a>
            <?php endif;?>
            <td>


                <a href="<?php echo App::config("url") ?>trophy/prepareedit/<?php echo $trophy->id ?>">
                    <i class="fas fa-edit fa-2x"></i>
                </a>

                <?php if($trophy->total==0): ?>
                    <a style="color: red;"
                     href="<?php echo App::config("url") ?>trophy/delete/<?php echo $trophy->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
                <?php endif; ?>
            
             </td>
        </tr>
        <?php endforeach;?>
        <?php endforeach;?>
    </tbody>
    
</table>