
<table class="grid-container">
    <thead>
        <tr>
            <th style="text-align: center">Trophy name</th>

        </tr>
    </thead>
    <tbody class="cell large-3">

        <?php foreach($trophys as $trophy): ?>
        <tr>
            <?php if($trophy->id === "1"): ?>
                <td class="success callout operators">
            <a href="<?= App::config("url")?>team_trophy/republicLeague"> <?= $trophy->trophy_name ?></a>
              </td>

            <?php elseif($trophy->id ==="2"): ?>
                <td class="success callout operators">
                    <a href="<?= App::config("url")?>team_trophy/republicCup"> <?= $trophy->trophy_name ?></a>
                </td>

            <?php elseif($trophy->id ==="3"): ?>
                <td class="success callout operators">
                    <a href="<?= App::config("url")?>team_trophy/republicSuperCup"> <?= $trophy->trophy_name ?></a>
                </td>
              <?php endif; ?>
        </tr>

        <?php endforeach; ?>

    </tbody>

</table>
