<table>
    <?php foreach($trophys as $trophy): ?>
        <?php foreach ($trophyWin as $tt): ?>
            <?php if($trophy->id === $tt ->trophy): ?>

                <hr style="border-bottom: 2px solid #aba6bf;" />
                <img style="width: 200px; height: 200px; float: right" alt="" src="<?=$trophy->photo ?>">
                <h2 style="margin-top: 50px; margin-bottom: 50px; color: #38003c;"> <?= $trophy->trophy_name;break ?></h2>



            <?php endif; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
    <thead>
    <tr>

        <th>Team</th>
        <th></th>
        <th>Years won</th>


    </tr>
    </thead>
    <tbody>


    <?php foreach($trophys as $trophy): ?>

        <?php foreach ($trophyWin as $tt): ?>
            <?php if($trophy->id === $tt ->trophy): ?>



                <tr>


                    <td style="font-size: 35px;">
                        <?= $tt ->title ?>
                    </td>

                    <td>
                         <img style="width: 100px; height: 100px;" alt="" src="<?php echo $tt->logo ?>">
                    </td>


                    <td style="font-size: 35px;">
                        <?= $tt ->year_won ?>
                    </td>



                </tr>
            <?php endif; ?>

        <?php endforeach; ?>

    <?php endforeach; ?>
    </tbody>


</table>