<?php foreach($trophys as $trophy): ?>


    <?php if($trophy->id ==="1"): ?>

        <h4><a href="<?= App::config("url")?>team_trophy/republicLeague"> <?= $trophy->trophy_name ?></a></h4>


    <?php endif ?>




        <table>

            <thead>
            <tr>
                <th>Team</th>
                <th>year won</th>
                <th>Times won</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
    <?php foreach ($trophyWin as $tt): ?>
        <?php if($trophy->id === $tt ->trophy)  : ?>



                <tr>

                    <td>
                        <?= $tt ->title ?>

                    </td>

                    <td>
                        <?= $tt ->yearWin ?>
                    </td>

                    <td>
                        <?= $tt ->times_won ?>
                    </td>
                </tr>
            <?php endif ?>
        <?php endforeach; ?>
            </tbody>


        </table>


<?php endforeach; ?>