<?php foreach($trophys as $trophy): ?>
    <img style="width: 200px; height: 200px; float: right" alt="" src="<?php echo $trophy->photo ?>">

    <?php if($trophy->id ==="1"): ?>

        <h4><a href="<?= App::config("url")?>team_trophy/republicLeague"> <?= $trophy->trophy_name ?></a></h4>


    <?php endif ?>




        <table>

            <thead>
            <tr>

                <th>Team</th>
                <th>year won</th>
                <th>Times won</th>

            </tr>
            </thead>
            <tbody>
    <?php foreach ($trophyWin as $tt): ?>
        <?php if($trophy->id === $tt ->trophy): ?>


                <tr>

                    <td>
                        <?= $tt ->title ?>

                    </td>

                    <td>
                        <?= $tt ->year_won ?>
                    </td>

                    <td>
                        <?= $tt ->times_won ?>
                    </td>

                </tr>
            <?php endif ?>
        <?php endforeach; ?>
            </tbody>


        </table>


<?php endforeach; ?>