<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>admin/login">

  <label>Email  </label>
        <input type="email" name="email" value="<?php  if(isset ($_POST["email"])) {
        echo Request::post("email");
        }else {
            echo App::config("dev") ? "baro.kristijan@gmail.com" : "";
        } ?>">


  <label>Password  </label>
    <input type="password" name="password"  value="<?php if(!isset($_POST["email"])){
        echo App::config("dev") ? "e" : "";
    }?>
        ">


 
   <button type="submit" class="button expanded" value="Log in">LOGIN</button>

</form>
<?php echo $message ?>


