<div class="grid-x">
    <div class="large-12 medium-12 small-12 columns">
        <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
            <button class="menu-icon" type="button" data-toggle="example-menu"></button>
            <div class="title-bar-title">Menu</div>
        </div>

        <div class="top-bar" id="example-menu">
            <div class="top-bar-left">
                <ul class="dropdown menu" data-dropdown-menu>

                    <li>
                        <a href="<?php echo App::config("url")."index" ?>">Home</a>

                    </li>
                    <li>
                        <a href="<?php echo App::config("url")."about" ?>">About</a>
                    </li>
                    <li>
                        <a href="<?php echo App::config("url")."contact" ?>">Contact</a>
                    </li>

                    <?php if(Session::getInstance()->isLogiran()): ?>
                    <li>
                        <a href="<?php echo App::config("url")."team/index" ?>">Teams</a>
                    </li>
                    <li>
                        <a href="<?php echo App::config("url")."operator/index" ?>">Operators</a>
                    </li>
                    <?php endif; ?>


                </ul>
            </div>
            <div class="top-bar-right">
                <ul class="menu">
                    <li>
                        <?php if(Session::getInstance()->isLogiran()): ?>
                        <a href="<?php echo App::config("url") ?>admin/logout">Logout
                            <?php echo Session::getInstance()->getUser()->nameSurname ?>
                        </a>
                        <?php else:?>
                        <a href="<?php echo App::config("url") ?>admin/login">Login</a>
                        <?php endif;?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>