<form class="log-in-form" method="post"
      action="<?php echo App::config("url") ?>user/registration">

    <label>Username</label>
    <input type="text" name="username" placeholder="Username" required>

    <label>Email</label>
    <input type="email" name="email" placeholder="Email" required>

    <label>Password</label>
    <input type="password" name="password"  placeholder="Password" required>


    <button type="submit" name="register_button" class="button expanded" value="Register">REGISTER</button>

</form>
<?php echo $message ?>


