<form class="log-in-form" method="post"
      action="<?php echo App::config("url") ?>user/register">


    <label>First name</label>
    <input type="text" name="reg_fname"  placeholder="First Name" required>

    <label>Last name</label>
    <input type="text" name="reg_lname"  placeholder="Last Name" required>

    <label>Email</label>
    <input type="email" name="reg_email" placeholder="Email" required>

    <label>Repeat Email</label>
    <input type="email" name="reg_email2" placeholder="Repeat Email" required>

    <label>Password</label>
    <input type="password" name="password"  placeholder="Password" required>

    <label>Repeat Password</label>
    <input type="password" name="password2"  placeholder="Repeat Password" required>


    <button type="submit" name="register_button" class="button expanded" value="Register">REGISTER</button>

</form>
<?php echo $message ?>


