<form class="log-in-form" method="post"
      action="<?php echo App::config("url") ?>admin/register">

    <label>Name</label>
    <input type="text" name="name" placeholder="Name" required>

    <label>Surname</label>
    <input type="text" name="surname" placeholder="Surname" required>


    <label>Email</label>
    <input type="email" name="email" placeholder="Email" required>

    <label>Password</label>
    <input type="password" name="password"  placeholder="Password" required>


    <button type="submit" name="register_button" class="button expanded" value="Register">REGISTER</button>

</form>
<?php echo $message ?>


