<label>Name
    <input type="text" name="name"
           value="<?php echo Request::post("name") ?>" />
</label>
<label>Surname
    <input type="text" name="surname"
           value="<?php echo Request::post("surname") ?>" />
</label>

<label for="favorite_team">Favorite team</label>
<select name="favorite_team" id="favorite_team">
    <option value="0">Choose</option>

    <?php foreach(Team::readFavorite() as $team): ?>

        <option

            <?php if(Request::post("favorite_team") == $team->id):?>
                selected="selected"
            <?php endif;?>

                value="<?php echo $team->id ?>"><?php echo $team->title ?>
        </option>

    <?php endforeach; ?>

</select>
<label>E-mail
    <input type="email" name="email"
           value="<?php echo Request::post("email") ?>" />
</label>

