<form class="log-in-form" method="post"
      action="<?php echo App::config("url") ?>operators/edit/<?php echo Request::post("id") ?>">

    <?php include_once "control.phtml" ?>

    <div class="grid-x">
        <div class="large-6 columns" style="padding: 10px;">
            <a href="<?php echo App::config("url") ?>operators/index" class="alert button expanded">
                Abort
            </a>
        </div>
        <div class="large-6 columns"  style="padding: 10px;">
            <input type="submit" class="success button expanded" value="Edit" />
        </div>
    </div>


</form>
<?php echo $message ?><?php
