<?php
$head = "<link rel=\"stylesheet\" href=\"" . APP::config("url") . "public/css/cropper.css\">";

$js="
  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js\"></script>
  <script src=\"https://fengyuanchen.github.io/js/common.js\"></script>
  <script src=\"" . APP::config("url") . "public/js/cropper.js\"></script>
  <script>let path=\"" . APP::config("url") .  "\";</script>
 <script src=\"" . APP::config("url") . "public/js/operators/index.js\"></script>
 
 ";
?>

<div class="grid-x">
    <?php foreach($operators as $operator): ?>
    <div class="cell large-3">
        <div class="success callout operators">

            <img id="operator_<?php echo $operator->id; ?>" class="picture" src="<?php

            $path = file_exists(App::config("path") . "public/img/operators/" . $operator->id . ".png")
                ?  App::config("url") . "public/img/operators/" . $operator->id . ".png"
                : App::config("url") . "public/img/unknown.png";

            echo $path ?>" alt="" />

            <h1><?php echo $operator->name?>
    <br />
    <?php echo $operator->surname?>
    </h1>
    <?php echo $operator->email?>

    </div>
    </div>

    <?php endforeach; ?>
</div>

<div class="reveal" id="pictureModal" data-reveal>
    <img id="image" src="" alt="" />
    <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
    <a href="#" id="save">Save</a>

    <button class="close-button" data-close aria-label="Close reveal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

