<label>Title
    <input type="text" name="title" 
    value="<?php echo Request::post("title") ?>" />
  </label>

<label for="manager">Manager</label>
<select name="manager" id="manager">
    <option value="0">Choose</option>

    <?php foreach(Manager::read() as $manager): ?>

        <option

            <?php if(Request::post("manager") == $manager->id):?>
                selected="selected"
            <?php endif;?>

                value="<?php echo $manager->id ?>"><?php echo $manager->name . " " . $manager->surname  ?></option>

    <?php endforeach; ?>

</select>
  <label>Ground
    <input type="text" name="ground"
    value="<?php echo Request::post("ground") ?>" />
  </label>

  <label>Ground Capacity
    <input type="number" name="ground_capacity"
    value="<?php echo Request::post("ground_capacity") ?>" />
  </label>

  <label>Since
    <input type="number" name="since" 
    value="<?php echo Request::post("since") ?>" />
  </label>

  <label>City
    <input type="text" name="city" 
    value="<?php echo Request::post("city") ?>" />
  </label>
