<label>Title
    <input type="text" name="title" 
    value="<?php echo Request::post("title") ?>" />
  </label>

  <label>Manager
    <input type="text" name="manager"
    value="<?php echo Request::post("manager") ?>" />
  </label>

  <label>Ground
    <input type="text" name="ground"
    value="<?php echo Request::post("ground") ?>" />
  </label>

  <label>Ground Capacity
    <input type="number" name="ground_capacity"
    value="<?php echo Request::post("ground_capacity") ?>" />
  </label>

  <label>Since
    <input type="number" name="since" 
    value="<?php echo Request::post("since") ?>" />
  </label>

    <label>Times won league
        <input type="number" name="times_won_league"
               value="<?php echo Request::post("times_won_league") ?>" />
    </label>

    <label>Times won cup
        <input type="number" name="times_won_cup"
               value="<?php echo Request::post("times_won_cup") ?>" />
    </label>

    <label>Times won supercup
        <input type="number" name="times_won_supercup"
               value="<?php echo Request::post("times_won_supercup") ?>" />
    </label>

  <label>City
    <input type="text" name="city" 
    value="<?php echo Request::post("city") ?>" />
  </label>
