
<a href="<?php echo App::config("url") ?>team/prepareadd" class="success button expanded">
    ADD NEW TEAM
</a>

<form  method="post" action="<?php echo App::config("url") ?>team/search">
    Search: <input type="text" name="search" value="<?php echo $_POST["search"] ?>" />

    <input class="button" type="submit" value="Search" />

</form>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Manager</th>
            <th>Ground</th>
            <th>Ground Capacity</th>
            <th>Since</th>
            <th>League</th>
            <th>Cup</th>
            <th>Supercup</th>
            <th>City</th>
            <th>Edit / Delete</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($teams as $team): ?>
        <tr>
            <td><?php echo $team->title ?></td>
            <td><?php echo $team->manager ?></td>
            <td><?php echo $team->ground ?></td>
            <td><?php echo $team->ground_capacity ?></td>
            <td><?php echo $team->since ?></td>
            <td><?php echo $team->times_won_league ?></td>
            <td><?php echo $team->times_won_cup ?></td>
            <td><?php echo $team->times_won_supercup ?></td>
            <td><?php echo $team->city ?></td>

            <td> 
                <a href="<?php echo App::config("url") ?>team/prepareedit/<?php echo $team->id ?>">
                    <i class="fas fa-edit fa-2x"></i>
                </a>

                <?php if($team->total==0): ?>
                    <a style="margin-left: 10px"
                     href="<?php echo App::config("url") ?>team/delete/<?php echo $team->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
                <?php endif; ?>
            
             </td>
        </tr>
        <?php endforeach;?>
    </tbody>

</table>
