
<a href="<?php echo App::config("url") ?>team/prepareadd" class="success button expanded">
    ADD NEW TEAM
</a>

<form  method="post" action="<?php echo App::config("url") ?>team/search">
    Search: <input type="text" name="search" value="<?php echo $_POST["search"] ?>" />

    <input class="button" type="submit" value="Search" />

</form>

<table>
    <thead>
        <tr>
            <th></th>
            <th>Title</th>
            <th>Manager</th>
            <th>Ground</th>
            <th>Ground Capacity</th>
            <th>Since</th>
            <th>City</th>
            <?php if(Session::getInstance()->getUser()->role==="admin"): ?>
            <th>Edit / Delete</th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($teams as $team): ?>
        <tr>
            <td><img style="width: 100px; height: 100px;" alt="" src="<?php echo $team->logo ?>"></td>
            <td><?php echo $team->title ?></td>
            <td><?php echo $team->manager ?></td>
            <td><?php echo $team->ground ?></td>
            <td><?php echo $team->ground_capacity ?></td>
            <td><?php echo $team->since ?></td>
            <td><?php echo $team->city ?></td>


            <td> 
                <a href="<?php echo App::config("url") ?>team/prepareedit/<?php echo $team->id ?>">
                    <i class="fas fa-edit fa-2x"></i>
                </a>

                <?php if(Session::getInstance()->getUser()->role==="admin"): ?>
                <?php if($team->total==0): ?>
                    <a style="margin-left: 10px"
                     href="<?php echo App::config("url") ?>team/delete/<?php echo $team->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
                <?php endif; ?>

                <?php endif; ?>
             </td>

        </tr>
        <?php endforeach;?>
        <nav aria-label="Pagination">
            <ul class="pagination text-center">
                <li class="pagination-previous"><a href="<?php echo App::config("url") ?>team/index/<?php echo $previous ?>" aria-label="Next page">Previous <span class="show-for-sr">page</span></a></li>
                <li class="pagination-next"><a href="<?php echo App::config("url") ?>team/index/<?php echo $next ?>" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
            </ul>
        </nav>
    </tbody>

</table>
