<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>teams/add">

 <?php include_once "control.phtml" ?>
 
 <div class="grid-x">
    <div class="large-6 columns" style="padding: 10px;">
        <a href="<?php echo App::config("url") ?>teams/index" class="alert button expanded">Abort</a>
    </div>
    <div class="large-6 columns"  style="padding: 10px;">
        <input type="submit" class="button expanded" value="Add new" />
    </div>
 </div>
  
 

</form>
<?php echo $poruka ?>
