<label>Name
    <input type="text" name="name"
           value="<?php echo Request::post("name") ?>" />
</label>

<label>Surname
    <input type="text" name="surname"
           value="<?php echo Request::post("surname") ?>" />
</label>

<label>Nationality
    <input type="text" name="nationality"
           value="<?php echo Request::post("nationality") ?>" />
</label>

<label for="positions">Position</label>
<select name="positions" id="positions">
    <option value="0">Choose</option>

    <?php foreach(Positions::read() as $positions): ?>

        <option

            <?php if(Request::post("position") == $positions->id):?>
                selected="selected"
            <?php endif;?>

                value="<?php echo $positions->id ?>"><?php echo $positions->position_name ?></option>

    <?php endforeach; ?>

</select>


<label>Salary
    <input type="number" name="salary"
           value="<?php echo Request::post("salary") ?>" />
</label>

<label for="team">Team</label>
<select name="team" id="team">
    <option value="0">Choose</option>

    <?php foreach(Team::read() as $team): ?>

        <option

            <?php if(Request::post("team") == $team->id):?>
                selected="selected"
            <?php endif;?>

                value="<?php echo $team->id ?>"><?php echo $team->title ?></option>

    <?php endforeach; ?>

</select>

