<label>Name
    <input type="text" name="name"
           value="<?php echo Request::post("name") ?>" />
</label>

<label>Surname
    <input type="text" name="surname"
           value="<?php echo Request::post("surname") ?>" />
</label>

<label>Nationality
    <input type="text" name="nationality"
           value="<?php echo Request::post("nationality") ?>" />
</label>

<label>Position
    <select type="text" name="position">
        <option value="<?php echo Request::post("position") ?>">--Select Position--</option>
        <option value="<?php echo Request::post("position") ?>">Striker</option>
        <option value="<?php echo Request::post("position") ?>">Midfielder</option>
        <option value="<?php echo Request::post("position") ?>">Defender</option>
        <option value="<?php echo Request::post("position") ?>">Goalkeeper</option>
    </select>
</label>

<label>Salary
    <input type="number" name="salary"
           value="<?php echo Request::post("salary") ?>" />
</label>

<label>Team
    <input type="number" name="team"
           value="<?php echo Request::post("team") ?>" />
</label>


