<a href="<?php echo App::config("url") ?>player/prepareadd" class="success button expanded">
   ADD NEW PLAYER
</a>

<form action="player.php" method="get">
    Search: <input type="text" name="search" value="<?php echo $_GET["search"]; ?>" /><input type="submit" value="Search" />
    <input name="show" type="radio" value="1"<?php if ($_GET["name"]=='1' or !isset($_GET["search"])) echo ' checked="checked"'; ?> />Name
    <input name="show" type="radio" value="2"<?php if ($_GET["surname"]=='1' or !isset($_GET["search"])) echo ' checked="checked"'; ?> />Surname
    <input name="show" type="radio" value="3"<?php if ($_GET["nationality"]=='1' or !isset($_GET["search"])) echo ' checked="checked"'; ?> />Nationality
    <input name="show" type="radio" value="4"<?php if ($_GET["position"]=='1' or !isset($_GET["search"])) echo ' checked="checked"'; ?> />Position
    <input name="show" type="radio" value="5"<?php if ($_GET["title"]=='1' or !isset($_GET["search"])) echo ' checked="checked"'; ?> />Team


</form>

<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Surname</th>
        <th>Nationality</th>
        <th>Position</th>
        <th>Salary</th>
        <th>Team</th>
        <th>Edit / Delete</th>

    </tr>
    </thead>
    <tbody>
    <?php foreach($players as $player): ?>
        <tr>
            <td><?php echo $player->name ?></td>
            <td><?php echo $player->surname ?></td>
            <td><?php echo $player->nationality ?></td>
            <td><?php echo $player->position ?></td>
            <td><?php echo $player->salary ?></td>
            <td><?php echo $player->title ?></td>

            <td>
                <a href="<?php echo App::config("url") ?>player/prepareedit/<?php echo $player->id ?>">
                    <i class="fas fa-edit fa-2x"></i>
                </a>

                
                    <a style="margin-left: 20px;"
                     href="<?php echo App::config("url") ?>player/delete/<?php echo $player->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
               
            

            </td>
        </tr>


    <?php endforeach;?>
    <nav aria-label="Pagination">
        <ul class="pagination text-center">
            <li class="pagination-previous"><a href="<?php echo App::config("url") ?>player/index/<?php echo $previous ?>" aria-label="Next page">Previous <span class="show-for-sr">page</span></a></li>
            <li class="pagination-next"><a href="<?php echo App::config("url") ?>player/index/<?php echo $next ?>" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        </ul>
    </nav>
    </tbody>



</table>