<a href="<?php echo App::config("url") ?>player/prepareadd" class="success button expanded">
   ADD NEW PLAYER
</a>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Surname</th>
        <th>Nationality</th>
        <th>Position</th>
        <th>Salary</th>
        <th>Team</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($players as $player): ?>
        <tr>
            <td><?php echo $player->name ?></td>
            <td><?php echo $player->surname ?></td>
            <td><?php echo $player->nationality ?></td>
            <td><?php echo $player->position ?></td>
            <td><?php echo $player->salary ?></td>
            <td><?php echo $player->team ?></td>

            <td>
                <a href="<?php echo App::config("url") ?>player/prepareedit/<?php echo $player->id ?>">
                    <i class="fas fa-edit fa-2x"></i>
                </a>

                <?php if($player->total==0): ?>
                    <a style="color: red;"
                       href="<?php echo App::config("url") ?>player/delete/<?php echo $player->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
                <?php endif; ?>

            </td>
        </tr>
    <?php endforeach;?>
    </tbody>

</table>