<?php if (is_array($players) || is_object($players)): ?>
    <?php if (Session::getInstance()->isLogiran()): ?>
        <div class="grid-x">
            <?php foreach($players as $player): ?>
                <div class="cell large-3">
                    <div class="success callout operators">
                        <h1><?php echo $player->name?>
                            <br />
                            <?= $player->numberOfPlayers?>
                        </h1>


                    </div>
                </div>

            <?php endforeach; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>