

<iframe id="sofa-standings-embed-1-17359" width="100%" height="726px" style="height:726px!important" src="https://www.sofascore.com/hr/turnir/1/17359/tablica/tablice/ugradi" frameborder="0" scrolling="no"></iframe><div style="font-size:12px;font-family:Arial,sans-serif"><a target="_blank" href="https://www.sofascore.com/hr/">Rezultati</a> by SofaScore</div><script type="text/javascript" src="https://www.sofascore.com/bundles/sofascoreweb/js/bin/util/embed.min.js"></script><script type="text/javascript">sofa_embed('sofa-standings-embed-1-17359', window);</script>
