<div class="grid-x">
    <?php foreach($users as $user): ?>
        <div class="cell large-3">
            <div class="success callout users">
                <h1><?php echo $user->first_name?>
                    <br />
                    <?php echo $user->last_name?>
                </h1>
                <?php echo $user->email?>

            </div>
        </div>

    <?php endforeach; ?>
</div>
