
<form  method="post" action="<?php echo App::config("url") ?>fixtures/search">
    Search: <input type="search" name="search" value="<?php echo $_POST["search"] ?>" />


    <input class="button" type="submit" value="Search" />

</form>



<table>
    <thead>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Home Team</th>
        <th>Home Goals</th>
        <th>Away Team</th>
        <th>Away Goals</th>
        <th>Referee</th>
        <?php if(Session::getInstance()->getUser()->role==="admin"): ?>
            <th>Edit / Delete</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach($fixtures as $fixture): ?>
        <tr>
            <td><?php echo $fixture->f_date ?></td>
            <td><?php echo $fixture->f_time ?></td>
            <td><?php echo $fixture->home_team ?></td>
            <td><?php echo $fixture->home_goals_for ?></td>
            <td><?php echo $fixture->away_team ?></td>
            <td><?php echo $fixture->away_goals_for ?></td>
            <td><?php echo $fixture->referee ?></td>


            <?php if(Session::getInstance()->getUser()->role==="admin"): ?>

                <td>
                    <a href="<?php echo App::config("url") ?>fixtures/prepareedit/<?php echo $fixture->id ?>">
                        <i class="fas fa-edit fa-2x"></i>
                    </a>


                    <a style="margin-left: 20px;"
                       href="<?php echo App::config("url") ?>fixtures/delete/<?php echo $fixture->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>



                </td>
            <?php endif; ?>
        </tr>


    <?php endforeach;?>
    <nav aria-label="Pagination">
        <ul class="pagination text-center">
            <li class="pagination-previous"><a href="<?php echo App::config("url") ?>fixtures/index/<?php echo $previous ?>" aria-label="Next page">Previous <span class="show-for-sr">page</span></a></li>
            <li class="pagination-next"><a href="<?php echo App::config("url") ?>fixtures/index/<?php echo $next ?>" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        </ul>
    </nav>

    </tbody>



</table>